### ISSUE TITLE
Краш при  wait_for_response = False

### ISSUE THREAD

**Issue by qweqwdsfbsdfsdfsdf** [Alex0007/website_load#3]
C:\Users\User\Desktop\website_load-master>1.py
12 user agents detected
2 urls detected
150 proxies detected
3000 threads
Flooding site.com
Traceback (most recent call last):
  File "C:\Users\User\Desktop\website_load-master\1.py", line 127, in <module>
    start_flood()
  File "C:\Users\User\Desktop\website_load-master\1.py", line 88, in start_flood

    future_to_url = {executor.submit(flood)}
  File "C:\Python34\lib\concurrent\futures\thread.py", line 105, in submit
    self._adjust_thread_count()
  File "C:\Python34\lib\concurrent\futures\thread.py", line 121, in _adjust_thre
ad_count
    t.start()
  File "C:\Python34\lib\threading.py", line 850, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

win 8.1, настройки такие:
request_methods = ["POST"]
thread_limit = 3000
append_rand_string_to_url = False
min_timeout = 30
max_timeout = 30
wait_for_response = False

**Comment by Alex0007** [comment]
Every OS has it's own thread limit within one process.
